---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cartservice
  namespace: microservices-demo
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true" # автоматически обновляет если докер-имидж обновился в реестре
    flux.weave.works/tag.chart-image: semver:~v0.0 # обновляются только такие версии
spec:
  releaseName: cartservice
  helmVersion: v3
  chart: # какой helm-чарт развоваричает
    git: git@gitlab.com:otushwo/microservices-demo.git
    ref: master
    path: deploy/charts/cartservice
  values:
    image:
      repository: dem0niuz/cartservice
      tag: v0.0.5
