apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - image: dem0niuz/paymentservice:v0.0.1
        name: paymentservice
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_DEBUGGER
          value: "1"
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
#        env:
#        - name: PORT
#          value: "8000"
#        - name: PRODUCT_CATALOG_SERVICE_ADDR
#          value: "localhost"
#        - name: CURRENCY_SERVICE_ADDR
#          value: "localhost"
#        - name: CART_SERVICE_ADDR
#          value: "localhost"
#        - name: RECOMMENDATION_SERVICE_ADDR
#          value: "localhost"
#        - name: SHIPPING_SERVICE_ADDR
#          value: "localhost"
#        - name: CHECKOUT_SERVICE_ADDR
#          value: "localhost"
#        - name: AD_SERVICE_ADDR
#          value: "localhost"
